Repository ArmandoBraho/3FA132-team1, pull requests merged in 2024-12, with the labels that each got.

#45 Added local setup-scripts for mainly mariadb
  setup_scripts/mariadb_start_skripte/mysql_cli.bat
  setup_scripts/mariadb_start_skripte/mysql_start.bat
  setup_scripts/mariadb_start_skripte/mysql_stop.bat
  setup_scripts/mariadb_start_skripte/setup_mariadb.sql
  setup_scripts/powershell_profileFile/Microsoft.PowerShell_profile.ps1
Labels: enhancement, Local

#47 Revert "Added local setup-scripts for mainly mariadb"
  setup_scripts/mariadb_start_skripte/mysql_cli.bat
  setup_scripts/mariadb_start_skripte/mysql_start.bat
  setup_scripts/mariadb_start_skripte/mysql_stop.bat
  setup_scripts/mariadb_start_skripte/setup_mariadb.sql
  setup_scripts/powershell_profileFile/Microsoft.PowerShell_profile.ps1
Labels: bug, Local

#49 Local setup script for mainly mariadb.
  setup_scripts/Altlast_skripte/dump_gm1_start/create_db_gm.sql
  setup_scripts/Altlast_skripte/dump_gm1_start/create_tables_gm1_mitarbeiter.sql
  setup_scripts/Altlast_skripte/gm3_scripts/create_view_gm3.sql
  setup_scripts/Altlast_skripte/gm3_scripts/dump_gm3_start.sql
  setup_scripts/mariadb_start_skripte/mysql_cli.bat
  setup_scripts/mariadb_start_skripte/mysql_start.bat
  setup_scripts/mariadb_start_skripte/mysql_stop.bat
  setup_scripts/mariadb_start_skripte/setup_mariadb.sql
  setup_scripts/powershell_profileFile/Microsoft.PowerShell_profile.ps1
Labels: bug, enhancement, Local
